version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: piedrazul-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      # Base de datos por defecto
      POSTGRES_DB: piedrazul_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Script de inicialización para crear las 3 bases de datos aisladas
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: piedrazul-rabbitmq
    ports:
      # Puerto para la comunicación de Spring Boot
      - "5672:5672"
      # Puerto para el panel de administración web
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    restart: always

volumes:
  postgres-data: