server:
  port: 8082

spring:
  application:
    name: availability-service
  datasource:
    url: jdbc:postgresql://localhost:5432/availability_db
    username: postgres
    password: 05062927
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

springdoc:
  swagger-ui:
    path: /swagger-ui.html